name: Execute Notebook

on:
  schedule:
    # Runs at 1 PM ET = 17:00 UTC
    - cron: '0 17 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Jupyter
        run: |
          pip install notebook nbconvert

      - name: Execute notebook to new file if within date range
        run: |
          START_DATE="2025-07-07"
          END_DATE="2025-08-08"
          TODAY=$(date -u +"%Y-%m-%d")

          if [[ "$TODAY" >="$START_DATE" && "$TODAY" <= "$END_DATE" ]]; then
            jupyter nbconvert --to notebook --execute src/quant_recurrent.ipynb \
              --ExecutePreprocessor.timeout=3600 \
              --output src/quant_recurrent_new.ipynb
          else
            echo "Outside execution window. Skipping."
          fi

      - name: Commit and push new notebook
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add src/quant_recurrent_new.ipynb
          git commit -m "Add executed quant_recurrent_new notebook"
          git push
